/**
 * Self-host Clash Display + Satoshi from Fontshare.
 * Downloads the woff2 files into public/fonts and writes src/styles/fonts.selfhosted.css.
 * Uses curl so it works behind proxies that Node's fetch ignores.
 *
 *   npm run fonts
 */
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs'
import { spawnSync } from 'node:child_process'

const CSS_URL = 'https://api.fontshare.com/v2/css?f[]=clash-display@500,600,700&f[]=satoshi@400,500,700&display=swap'
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124 Safari/537.36'

function curl(url, out) {
  const r = spawnSync('curl', ['-sS', '-L', '-A', UA, '-o', out, '-w', '%{http_code}', url], { encoding: 'utf8' })
  if (r.status !== 0 || r.stdout.trim() !== '200') throw new Error(`curl ${url} → ${r.stdout} ${r.stderr}`)
}

mkdirSync('public/fonts', { recursive: true })
curl(CSS_URL, 'public/fonts/_fontshare.css')
let css = readFileSync('public/fonts/_fontshare.css', 'utf8')
const urls = [...new Set([...css.matchAll(/url\(['"]?([^'")]+\.woff2)['"]?\)/gi)].map((m) => m[1]))]
let i = 0
for (const u of urls) {
  const abs = u.startsWith('//') ? `https:${u}` : u
  const name = `${String(i++).padStart(2, '0')}-${u.split('/').pop().split('?')[0].toLowerCase()}`
  curl(abs, `public/fonts/${name}`)
  css = css.split(u).join(`/fonts/${name}`)
  console.log('saved', name)
}
// keep only the woff2 sources
css = css
  .replace(/,?\s*url\(['"]?[^'")]+\.(?:woff|ttf|otf|eot)['"]?\)\s*format\(['"][^'"]+['"]\)/gi, '')
  .replace(/src:\s*,/g, 'src:')
css = `/* Generated by scripts/fetch-fonts.mjs — Clash Display + Satoshi, self-hosted (Fontshare, ITF Free Font License). */\n` + css
writeFileSync('src/styles/fonts.selfhosted.css', css)
console.log('wrote src/styles/fonts.selfhosted.css with', urls.length, 'faces')
